apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: app
type: Opaque
stringData:
  # PostgreSQL expects these exact variable names
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres"
  POSTGRES_DB: "fastdb"
  # These are for the app to connect
  DB_USER: "postgres"
  DB_PASSWORD: "postgres"
  DB_NAME: "fastdb"
  
  # the application requires these if used in other environments
  JWT_SECRET: "a-very-long-random-string-12345"
