---
# This tells the operator WHICH AWS service to connect to
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secretsmanager
  namespace: app
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1

---
# This tells the operator WHAT to fetch and what to name it in Kubernetes
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-external-secret
  namespace: app
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: postgres-secret # Your pods will look for a secret with this exact name!
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: prod/smalllinks/db-secrets