apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: app
  labels:
    app: smalllinks
data:
  BASE_URL: "a0f502e60e6804f99ae5e0525cfcc40b-1400791037.us-east-1.elb.amazonaws.com"
  PORT: "8201"
  SHORTENER_DEBUG: "true"
  SHORT_URL_LENGTH: "5"
  SHORT_KEY_GENERATION_RETRIES_COUNT: "5"
  KAFKA_HOST: "broker:9092"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  DB_HOST: "postgres"
  DB_PORT: "5432"
  LOG_LEVEL: "info"