apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: smalllinks-monitor
  namespace: observability
spec:
  namespaceSelector:
    matchNames:
      - app
  selector:
    matchLabels:
      app: smalllinks # Matches the labels on your deployment/service
  endpoints:
    - targetPort: 8201
      path: /metrics
      interval: 15s