apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: smalllinks-monitor
  namespace: observability
  labels:
    release: observability-stack   # <--- THIS IS THE MAGIC LABEL
spec:
  namespaceSelector:
    matchNames:
      - app
  selector:
    matchLabels:
      app: smalllinks
  endpoints:
    - targetPort: 8201
      path: /metrics
      interval: 15s